apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: sol
spec:
  ports:
  - port: 80
  selector:
    app: portal

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-conf
  namespace: sol
data:
  portal.conf: |
    server {
      listen  80;
      server_name  sol.xeno;
      gzip_static  on;
      location ^~ / {
        root  /usr/share/nginx/static;
        index  index.html;
      }
      location ^~ /api/auth/ {
        proxy_pass  http://auth-portal:8080/;
      }
      location ^~ /api/bing-image-meta/ {
        proxy_pass  https://www.bing.com/HPImageArchive.aspx/;
      }
    }

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal
  namespace: sol
spec:
  rules:
  - host: sol.xeno
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portal
            port:
              number: 80
