apiVersion: v1
kind: Service
metadata:
  name: auth-portal
  namespace: sol
spec:
  ports:
  - port: 8080
  selector:
    app: auth-portal

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-portal
  namespace: sol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-portal
  template:
    metadata:
      labels:
        app: auth-portal
        frontend: app
        backend: app
    spec:
      containers:
      - name: auth-portal
        image: chenzhe0722/sol:auth-portal
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: pre
      initContainers:
      - name: wait
        image: chenzhe0722/sol:wait
        command: ["wait-for", "-t", "5", "database:3306", "cache:6379"]
