apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: sol
spec:
  ports:
  - name: mysql
    port: 3306
  - name: mysql-x
    port: 33060
  selector:
    app: database

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: sol
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: sol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        backend: app
    spec:
      containers:
      - name: database
        image: chenzhe0722/sol:database
        ports:
        - containerPort: 3306
        - containerPort: 33060
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
