apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: sol
spec:
  ports:
  - port: 80
  selector:
    app: portal

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: sol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
        frontend: app
    spec:
      containers:
      - name: portal
        image: chenzhe0722/sol:portal
        ports:
        - containerPort: 80
      initContainers:
      - name: wait
        image: chenzhe0722/sol:wait
        command: ["wait-for", "-t", "5", "auth-portal:8080"]

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal
  namespace: sol
spec:
  rules:
  - host: sol.xeno
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portal
            port:
              number: 80
