apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: sol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
        frontend: app
    spec:
      containers:
      - name: portal
        image: chenzhe0722/sol:portal
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 8Mi
          limits:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - name: portal-conf
          mountPath: /etc/nginx/conf.d/portal.conf
          subPath: portal.conf
      initContainers:
      - name: wait
        image: chenzhe0722/sol:wait
        command: ["wait-for", "-t", "5", "auth-portal:8080"]
      volumes:
      - name: portal-conf
        configMap:
          name: portal-conf
