apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-relation
  namespace: sol
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relation
  namespace: sol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relation
  template:
    metadata:
      labels:
        app: relation
        backend: app
    spec:
      containers:
      - name: relation
        image: mysql/mysql-server:latest
        args: ["--relay-log=\"relation-relay-bin\""]
        ports:
        - containerPort: 3306
        - containerPort: 33060
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: data-relation
          mountPath: /var/lib/mysql
        - name: relation-init
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
      volumes:
      - name: data-relation
        persistentVolumeClaim:
          claimName: data-relation
      - name: relation-init
        configMap:
          name: relation-init
