fullnameOverride: cache
usePassword: false
persistence:
  enabled: false
redis:
  podLabels:
    backend: app
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 2000m
      memory: 8Gi
