fullnameOverride: relation
persistence:
  size: 1Gi
podLabels:
  backend: app
resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1Gi
initdbScripts:
  init.sql: |
    CREATE DATABASE auth DEFAULT CHARACTER SET utf8mb4;
    CREATE TABLE auth.account (
      id          SERIAL,
      name        VARCHAR(255)     NOT NULL,
      password    VARCHAR(255)     NOT NULL,
      status      TINYINT UNSIGNED NOT NULL,
      last_logged DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
      version     BIGINT UNSIGNED  NOT NULL DEFAULT 0,
      PRIMARY KEY (id),
      UNIQUE KEY (name)
    ) ENGINE = InnoDB;
    CREATE USER 'auth';
    GRANT SELECT, INSERT, UPDATE, DELETE ON auth.* TO 'auth';
