version: "3.8"

services:
  portal:
    image: chenzhe0722/sol:portal
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - auth-portal
    command: ["wait-for", "-t", "30", "auth-portal:8080", "--", "nginx", "-g", "daemon off;"]
  auth-portal:
    image: chenzhe0722/sol:auth-portal
    networks:
      - frontend
      - backend
    depends_on:
      - database
      - cache
    command: ["wait-for", "-t", "15", "database:3306", "cache:6379", "--", "java", "-jar", "app.jar", "--spring.profiles.active=prod"]
  auth-schedule:
    image: chenzhe0722/sol:auth-schedule
    networks:
      - backend
    depends_on:
      - database
    command: ["wait-for", "-t", "15", "database:3306", "--", "java", "-jar", "app.jar", "--spring.profiles.active=prod"]
  database:
    image: chenzhe0722/sol:database-master
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend
  cache:
    image: redis:alpine
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  data:
