apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: portal
          image: chenzhe0722/sol:portal
          ports:
            - containerPort: 80
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.nginxConf }}
          volumeMounts:
            {{- range $key, $_ := .Values.nginxConf }}
            - name: {{ $.Release.Name }}-conf
              mountPath: /etc/nginx/conf.d/{{ $key }}
              subPath: {{ $key }}
            {{- end }}
          {{- end }}
      initContainers:
        - name: {{ .Release.Name }}-wait
          image: chenzhe0722/sol:wait
          command:
            - "wait-for"
            - "-t"
            - {{ .Values.init.timeout | quote }}
            {{- range .Values.init.wait }}
            - {{ . | quote }}
            {{- end }}
      {{- if .Values.nginxConf }}
      volumes:
        - name: {{ .Release.Name }}-conf
          configMap:
            name: {{ .Release.Name }}-conf
      {{- end }}
