apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: chenzhe0722/sol:portal
        ports:
        - containerPort: 443
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: {{ .Release.Name }}-ssl
          mountPath: /usr/share/nginx/cert
        - name: {{ .Release.Name }}-conf
          mountPath: /etc/nginx/conf.d
      {{- if .Values.init }}
      initContainers:
      - name: {{ .Release.Name }}-wait
        image: chenzhe0722/sol:wait
        command:
        - "wait-for"
        - "-t"
        - {{ .Values.init.timeout | quote }}
        {{- range .Values.init.wait }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      volumes:
      - name: {{ .Release.Name }}-ssl
        secret:
          secretName: {{ .Values.ssl.secretName }}
      - name: {{ .Release.Name }}-conf
        configMap:
          name: {{ .Release.Name }}-conf
