apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-portal
  namespace: sol
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-portal
  template:
    metadata:
      labels:
        app: auth-portal
        frontend: app
        backend: app
    spec:
      containers:
      - name: auth-portal
        image: chenzhe0722/sol:auth-portal
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 20m
            memory: 256Mi
          limits:
            cpu: 2000m
            memory: 4Gi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: LOG4J_CONTEXT_SELECTOR
          value: org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
      initContainers:
      - name: wait
        image: chenzhe0722/sol:wait
        command: ["wait-for", "-t", "5", "relation:3306", "cache:6379"]
