apiVersion: v1
kind: Service
metadata:
  name: cache-cluster
  namespace: sol
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
  - name: bus
    port: 16379
  selector:
    app: cache

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache
  namespace: sol
spec:
  serviceName: cache-cluster
  replicas: 6
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
        backend: app
    spec:
      containers:
      - name: cache
        image: redis:alpine
        ports:
        - containerPort: 6379
        - containerPort: 16379
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 8000m
            memory: 32Gi
        volumeMounts:
        - name: cache-data
          mountPath: /data
        - name: cache-conf
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
      initContainers:
      - name: init
        image: busybox:latest
        command:
        - sh
        - "-c"
        - |
          set -eux
          echo "protected-mode no" > /root/redis/redis.conf
          echo "cluster-enabled yes" >> /root/redis/redis.conf
          echo "cluster-announce-ip cache-${HOSTNAME##*-}.cache-cluster.sol.svc.cluster.local" >> /root/redis/redis.conf
        volumeMounts:
        - name: cache-conf
          mountPath: /root/redis
      volumes:
      - name: cache-conf
        emptyDir:
          sizeLimit: 2Ki
      - name: cache-data
        emptyDir:
          sizeLimit: 64Ki

---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-cache
  namespace: sol
spec:
  template:
    spec:
      containers:
      - name: init-cache
        image: redis:alpine
        command:
        - sh
        - "-c"
        - |
          redis-cli --cluster create \
          $(cat /root/redis/info.txt) \
          --cluster-replicas 1 \
          --cluster-yes
        volumeMounts:
        - name: cache-info
          mountPath: /root/redis/info.txt
          subPath: info.txt
      initContainers:
      - name: wait
        image: chenzhe0722/sol:wait
        command:
        - sh
        - "-c"
        - |
          set -eux
          echo "" > /root/redis/info.txt
          for i in $(seq 0 5); do
            wait-for -t 5 "cache-${i}.cache-cluster.sol.svc.cluster.local:6379"
            nslookup -type=a "cache-${i}.cache-cluster.sol.svc.cluster.local" \
              | sed -n '/Name/{n;p;}' \
              | head -n 1 \
              | awk '{printf "%s:6379 ", $2}' >> /root/redis/info.txt
          done
          sed -i 's/ $//' /root/redis/info.txt
        volumeMounts:
        - name: cache-info
          mountPath: /root/redis
      volumes:
      - name: cache-info
        emptyDir:
          sizeLimit: 4Ki
      restartPolicy: OnFailure
