replicas: 3
podLabels:
  frontend: app
resources:
  requests:
    cpu: 10m
    memory: 8Mi
  limits:
    cpu: 500m
    memory: 256Mi
ssl:
  secretName: portal
ingress:
  host: sol.xeno
init:
  timeout: 5
  wait:
  - auth-portal:8443
nginxConf:
  portal.conf: |
    server {
      listen  443 ssl http2;
      server_name  sol.xeno;
      ssl_certificate  /usr/share/nginx/cert/tls.crt;
      ssl_certificate_key  /usr/share/nginx/cert/tls.key;
      gzip_static  on;
      location ^~ / {
        root  /usr/share/nginx/static;
        index  index.html;
      }
      location ^~ /api/auth/ {
        proxy_pass  https://auth-portal:8443/;
      }
      location ^~ /api/bing-image-meta/ {
        proxy_pass  https://www.bing.com/HPImageArchive.aspx/;
      }
    }
