#!/bin/sh

SOL_ROOT=$(dirname "${0}")

apply_kube() {
  while read CONF; do
    kubectl apply -f "${SOL_ROOT}/${1}/${CONF}"
  done < "${SOL_ROOT}/${2}"
}

apply_kube main main.conf
apply_kube "${1}" mode.conf
