name: sol

on:
  push:
    branches: ci

jobs:
  java:
    name: Build and Upload Java
    runs-on: ubuntu-latest
    container: maven:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build with Maven
      run: |
        mvn -B -fae -e -ntp clean package
      working-directory: java/sol
    - name: Upload auth-portal Artifact
      uses: actions/upload-artifact@v2
      with:
        name: java
        path: java/sol/auth/auth-portal/target/auth-portal.jar

  javascript:
    name: Build and Upload Javascript
    runs-on: ubuntu-latest
    container: node:lts
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build with Npm
      run: |
        npm install
        npm run-script build
      working-directory: javascript/sol
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: javascript
        path: javascript/sol/dist/

  docker-auth-portal:
    name: Dist Auth-Portal to DockerHub
    runs-on: ubuntu-latest
    needs: [java]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: java
        path: artifact
    - name: Move Artifact
      run: |
        mv artifact/auth-portal.jar docker/sol/springboot/app.jar
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DockerHubUser }}
        password: ${{ secrets.DockerHubToken }}
    - name: Build and Push sol:auth-portal
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chenzhe0722/sol:auth-portal
        context: docker/sol/springboot
        file: docker/sol/springboot/Dockerfile
        platforms: linux/amd64,linux/arm64

  docker-portal:
    name: Dist Portal to DockerHub
    runs-on: ubuntu-latest
    needs: [javascript]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: javascript
        path: artifact
    - name: Move Artifact
      run: |
        mv artifact docker/sol/nginx/static
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DockerHubUser }}
        password: ${{ secrets.DockerHubToken }}
    - name: Build and Push sol:portal
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chenzhe0722/sol:portal
        context: docker/sol/nginx
        file: docker/sol/nginx/Dockerfile
        platforms: linux/amd64,linux/arm64

  docker-wait:
    name: Dist Wait to DockerHub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DockerHubUser }}
        password: ${{ secrets.DockerHubToken }}
    - name: Build and Push sol:wait
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chenzhe0722/sol:wait
        context: docker/sol/wait
        file: docker/sol/wait/Dockerfile
        platforms: linux/amd64,linux/arm64

  docker-jks:
    name: Dist Jks to DockerHub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DockerHubUser }}
        password: ${{ secrets.DockerHubToken }}
    - name: Build and Push sol:jks
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chenzhe0722/sol:jks
        context: docker/sol/jks
        file: docker/sol/jks/Dockerfile
        platforms: linux/amd64,linux/arm64
