replicas: 3
podLabels:
  frontend: app
  backend: app
resources:
  requests:
    cpu: 20m
    memory: 256Mi
  limits:
    cpu: 2000m
    memory: 4Gi
init:
  timeout: 5
  wait:
    - relation:3306
    - cache:6379
